using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
namespace Phi.Interop.WinAPI.IO
{
    /// <summary>
    /// IO Control Codes
    /// Useful links:
    ///     http://www.ioctls.net/
    ///     http://msdn.microsoft.com/en-us/library/windows/hardware/ff543023(v=vs.85).aspx
    /// </summary>
    [Flags]
    public enum NativeDeviceIOControlCode : uint
    {
        // STORAGE
        StorageCheckVerify = (NativeDeviceIODevice.MassStorage << 16) | (0x0200 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        StorageCheckVerify2 = (NativeDeviceIODevice.MassStorage << 16) | (0x0200 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14), // FileAccess.Any
        StorageMediaRemoval = (NativeDeviceIODevice.MassStorage << 16) | (0x0201 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        StorageEjectMedia = (NativeDeviceIODevice.MassStorage << 16) | (0x0202 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        StorageLoadMedia = (NativeDeviceIODevice.MassStorage << 16) | (0x0203 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        StorageLoadMedia2 = (NativeDeviceIODevice.MassStorage << 16) | (0x0203 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        StorageReserve = (NativeDeviceIODevice.MassStorage << 16) | (0x0204 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        StorageRelease = (NativeDeviceIODevice.MassStorage << 16) | (0x0205 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        StorageFindNewDevices = (NativeDeviceIODevice.MassStorage << 16) | (0x0206 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        StorageEjectionControl = (NativeDeviceIODevice.MassStorage << 16) | (0x0250 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        StorageMcnControl = (NativeDeviceIODevice.MassStorage << 16) | (0x0251 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        StorageGetMediaTypes = (NativeDeviceIODevice.MassStorage << 16) | (0x0300 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        StorageGetMediaTypesEx = (NativeDeviceIODevice.MassStorage << 16) | (0x0301 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        StorageResetBus = (NativeDeviceIODevice.MassStorage << 16) | (0x0400 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        StorageResetDevice = (NativeDeviceIODevice.MassStorage << 16) | (0x0401 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        StorageGetDeviceNumber = (NativeDeviceIODevice.MassStorage << 16) | (0x0420 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        StoragePredictFailure = (NativeDeviceIODevice.MassStorage << 16) | (0x0440 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        StorageObsoleteResetBus = (NativeDeviceIODevice.MassStorage << 16) | (0x0400 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        StorageObsoleteResetDevice = (NativeDeviceIODevice.MassStorage << 16) | (0x0401 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        StorageQueryProperty = (NativeDeviceIODevice.MassStorage << 16) | (0x0500 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        // DISK
        DiskGetDriveGeometry = (NativeDeviceIODevice.Disk << 16) | (0x0000 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskGetDriveGeometryEx = (NativeDeviceIODevice.Disk << 16) | (0x0028 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskGetPartitionInfo = (NativeDeviceIODevice.Disk << 16) | (0x0001 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        DiskGetPartitionInfoEx = (NativeDeviceIODevice.Disk << 16) | (0x0012 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskSetPartitionInfo = (NativeDeviceIODevice.Disk << 16) | (0x0002 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskGetDriveLayout = (NativeDeviceIODevice.Disk << 16) | (0x0003 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        DiskSetDriveLayout = (NativeDeviceIODevice.Disk << 16) | (0x0004 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskVerify = (NativeDeviceIODevice.Disk << 16) | (0x0005 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskFormatTracks = (NativeDeviceIODevice.Disk << 16) | (0x0006 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskReassignBlocks = (NativeDeviceIODevice.Disk << 16) | (0x0007 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskPerformance = (NativeDeviceIODevice.Disk << 16) | (0x0008 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskIsWritable = (NativeDeviceIODevice.Disk << 16) | (0x0009 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskLogging = (NativeDeviceIODevice.Disk << 16) | (0x000a << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskFormatTracksEx = (NativeDeviceIODevice.Disk << 16) | (0x000b << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskHistogramStructure = (NativeDeviceIODevice.Disk << 16) | (0x000c << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskHistogramData = (NativeDeviceIODevice.Disk << 16) | (0x000d << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskHistogramReset = (NativeDeviceIODevice.Disk << 16) | (0x000e << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskRequestStructure = (NativeDeviceIODevice.Disk << 16) | (0x000f << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskRequestData = (NativeDeviceIODevice.Disk << 16) | (0x0010 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskControllerNumber = (NativeDeviceIODevice.Disk << 16) | (0x0011 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskSmartGetVersion = (NativeDeviceIODevice.Disk << 16) | (0x0020 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        DiskSmartSendDriveCommand = (NativeDeviceIODevice.Disk << 16) | (0x0021 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskSmartRcvDriveData = (NativeDeviceIODevice.Disk << 16) | (0x0022 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskUpdateDriveSize = (NativeDeviceIODevice.Disk << 16) | (0x0032 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskGrowPartition = (NativeDeviceIODevice.Disk << 16) | (0x0034 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskGetCacheInformation = (NativeDeviceIODevice.Disk << 16) | (0x0035 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        DiskSetCacheInformation = (NativeDeviceIODevice.Disk << 16) | (0x0036 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskDeleteDriveLayout = (NativeDeviceIODevice.Disk << 16) | (0x0040 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskFormatDrive = (NativeDeviceIODevice.Disk << 16) | (0x00f3 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskSenseDevice = (NativeDeviceIODevice.Disk << 16) | (0x00f8 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskCheckVerify = (NativeDeviceIODevice.Disk << 16) | (0x0200 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        DiskMediaRemoval = (NativeDeviceIODevice.Disk << 16) | (0x0201 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        DiskEjectMedia = (NativeDeviceIODevice.Disk << 16) | (0x0202 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        DiskLoadMedia = (NativeDeviceIODevice.Disk << 16) | (0x0203 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        DiskReserve = (NativeDeviceIODevice.Disk << 16) | (0x0204 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        DiskRelease = (NativeDeviceIODevice.Disk << 16) | (0x0205 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        DiskFindNewDevices = (NativeDeviceIODevice.Disk << 16) | (0x0206 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        DiskGetMediaTypes = (NativeDeviceIODevice.Disk << 16) | (0x0300 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskSetPartitionInfoEx = (NativeDeviceIODevice.Disk << 16) | (0x0013 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskGetDriveLayoutEx = (NativeDeviceIODevice.Disk << 16) | (0x0014 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        DiskSetDriveLayoutEx = (NativeDeviceIODevice.Disk << 16) | (0x0015 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskCreateDisk = (NativeDeviceIODevice.Disk << 16) | (0x0016 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        DiskGetLengthInfo = (NativeDeviceIODevice.Disk << 16) | (0x0017 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        // CHANGER
        ChangerGetParameters = (NativeDeviceIODevice.Changer << 16) | (0x0000 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        ChangerGetStatus = (NativeDeviceIODevice.Changer << 16) | (0x0001 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        ChangerGetProductData = (NativeDeviceIODevice.Changer << 16) | (0x0002 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        ChangerSetAccess = (NativeDeviceIODevice.Changer << 16) | (0x0004 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        ChangerGetElementStatus = (NativeDeviceIODevice.Changer << 16) | (0x0005 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        ChangerInitializeElementStatus = (NativeDeviceIODevice.Changer << 16) | (0x0006 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        ChangerSetPosition = (NativeDeviceIODevice.Changer << 16) | (0x0007 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        ChangerExchangeMedium = (NativeDeviceIODevice.Changer << 16) | (0x0008 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        ChangerMoveMedium = (NativeDeviceIODevice.Changer << 16) | (0x0009 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        ChangerReinitializeTarget = (NativeDeviceIODevice.Changer << 16) | (0x000A << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        ChangerQueryVolumeTags = (NativeDeviceIODevice.Changer << 16) | (0x000B << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        // FILESYSTEM
        FsctlRequestOplockLevel1 = (NativeDeviceIODevice.FileSystem << 16) | (0 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlRequestOplockLevel2 = (NativeDeviceIODevice.FileSystem << 16) | (1 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlRequestBatchOplock = (NativeDeviceIODevice.FileSystem << 16) | (2 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlOplockBreakAcknowledge = (NativeDeviceIODevice.FileSystem << 16) | (3 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlOpBatchAckClosePending = (NativeDeviceIODevice.FileSystem << 16) | (4 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlOplockBreakNotify = (NativeDeviceIODevice.FileSystem << 16) | (5 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlLockVolume = (NativeDeviceIODevice.FileSystem << 16) | (6 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlUnlockVolume = (NativeDeviceIODevice.FileSystem << 16) | (7 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlDismountVolume = (NativeDeviceIODevice.FileSystem << 16) | (8 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlIsVolumeMounted = (NativeDeviceIODevice.FileSystem << 16) | (10 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlIsPathnameValid = (NativeDeviceIODevice.FileSystem << 16) | (11 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlMarkVolumeDirty = (NativeDeviceIODevice.FileSystem << 16) | (12 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlQueryRetrievalPointers = (NativeDeviceIODevice.FileSystem << 16) | (14 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlGetCompression = (NativeDeviceIODevice.FileSystem << 16) | (15 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlSetCompression = (NativeDeviceIODevice.FileSystem << 16) | (16 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        FsctlMarkAsSystemHive = (NativeDeviceIODevice.FileSystem << 16) | (19 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlOplockBreakAckNo2 = (NativeDeviceIODevice.FileSystem << 16) | (20 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlInvalidateVolumes = (NativeDeviceIODevice.FileSystem << 16) | (21 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlQueryFatBpb = (NativeDeviceIODevice.FileSystem << 16) | (22 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlRequestFilterOplock = (NativeDeviceIODevice.FileSystem << 16) | (23 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlFileSystemGetStatistics = (NativeDeviceIODevice.FileSystem << 16) | (24 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlGetNtfsVolumeData = (NativeDeviceIODevice.FileSystem << 16) | (25 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlGetNtfsFileRecord = (NativeDeviceIODevice.FileSystem << 16) | (26 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlGetVolumeBitmap = (NativeDeviceIODevice.FileSystem << 16) | (27 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlGetRetrievalPointers = (NativeDeviceIODevice.FileSystem << 16) | (28 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlMoveFile = (NativeDeviceIODevice.FileSystem << 16) | (29 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlIsVolumeDirty = (NativeDeviceIODevice.FileSystem << 16) | (30 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlGetHfsInformation = (NativeDeviceIODevice.FileSystem << 16) | (31 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlAllowExtendedDasdIo = (NativeDeviceIODevice.FileSystem << 16) | (32 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlReadPropertyData = (NativeDeviceIODevice.FileSystem << 16) | (33 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlWritePropertyData = (NativeDeviceIODevice.FileSystem << 16) | (34 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlFindFilesBySid = (NativeDeviceIODevice.FileSystem << 16) | (35 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlDumpPropertyData = (NativeDeviceIODevice.FileSystem << 16) | (37 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlSetObjectId = (NativeDeviceIODevice.FileSystem << 16) | (38 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlGetObjectId = (NativeDeviceIODevice.FileSystem << 16) | (39 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlDeleteObjectId = (NativeDeviceIODevice.FileSystem << 16) | (40 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlSetReparsePoint = (NativeDeviceIODevice.FileSystem << 16) | (41 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlGetReparsePoint = (NativeDeviceIODevice.FileSystem << 16) | (42 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlDeleteReparsePoint = (NativeDeviceIODevice.FileSystem << 16) | (43 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlEnumUsnData = (NativeDeviceIODevice.FileSystem << 16) | (44 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlSecurityIdCheck = (NativeDeviceIODevice.FileSystem << 16) | (45 << 2) | NativeDeviceIOMethod.Neither | (FileAccess.Read << 14),
        FsctlReadUsnJournal = (NativeDeviceIODevice.FileSystem << 16) | (46 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlSetObjectIdExtended = (NativeDeviceIODevice.FileSystem << 16) | (47 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlCreateOrGetObjectId = (NativeDeviceIODevice.FileSystem << 16) | (48 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlSetSparse = (NativeDeviceIODevice.FileSystem << 16) | (49 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlSetZeroData = (NativeDeviceIODevice.FileSystem << 16) | (50 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Write << 14),
        FsctlQueryAllocatedRanges = (NativeDeviceIODevice.FileSystem << 16) | (51 << 2) | NativeDeviceIOMethod.Neither | (FileAccess.Read << 14),
        FsctlEnableUpgrade = (NativeDeviceIODevice.FileSystem << 16) | (52 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Write << 14),
        FsctlSetEncryption = (NativeDeviceIODevice.FileSystem << 16) | (53 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlEncryptionFsctlIo = (NativeDeviceIODevice.FileSystem << 16) | (54 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlWriteRawEncrypted = (NativeDeviceIODevice.FileSystem << 16) | (55 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlReadRawEncrypted = (NativeDeviceIODevice.FileSystem << 16) | (56 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlCreateUsnJournal = (NativeDeviceIODevice.FileSystem << 16) | (57 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlReadFileUsnData = (NativeDeviceIODevice.FileSystem << 16) | (58 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlWriteUsnCloseRecord = (NativeDeviceIODevice.FileSystem << 16) | (59 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlExtendVolume = (NativeDeviceIODevice.FileSystem << 16) | (60 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlQueryUsnJournal = (NativeDeviceIODevice.FileSystem << 16) | (61 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlDeleteUsnJournal = (NativeDeviceIODevice.FileSystem << 16) | (62 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlMarkHandle = (NativeDeviceIODevice.FileSystem << 16) | (63 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlSisCopyFile = (NativeDeviceIODevice.FileSystem << 16) | (64 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        FsctlSisLinkFiles = (NativeDeviceIODevice.FileSystem << 16) | (65 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        FsctlHsmMsg = (NativeDeviceIODevice.FileSystem << 16) | (66 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.ReadWrite << 14),
        FsctlNssControl = (NativeDeviceIODevice.FileSystem << 16) | (67 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Write << 14),
        FsctlHsmData = (NativeDeviceIODevice.FileSystem << 16) | (68 << 2) | NativeDeviceIOMethod.Neither | (FileAccess.ReadWrite << 14),
        FsctlRecallFile = (NativeDeviceIODevice.FileSystem << 16) | (69 << 2) | NativeDeviceIOMethod.Neither | (0 << 14),
        FsctlNssRcontrol = (NativeDeviceIODevice.FileSystem << 16) | (70 << 2) | NativeDeviceIOMethod.Buffered | (FileAccess.Read << 14),
        // VIDEO
        VideoQuerySupportedBrightness = (NativeDeviceIODevice.Video << 16) | (0x0125 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        VideoQueryDisplayBrightness = (NativeDeviceIODevice.Video << 16) | (0x0126 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14),
        VideoSetDisplayBrightness = (NativeDeviceIODevice.Video << 16) | (0x0127 << 2) | NativeDeviceIOMethod.Buffered | (0 << 14)
    }
}
